syntax = "proto3";

package neko;

message Key {
    string id = 1;
    uint64 version = 2;
    string unique_name = 3;
}

message Stock {
    Key key = 1;
    string name = 2;
    string bbg_id = 3;
    string cusip = 4;
    string isin = 5;
    string ibkr_contract_id = 6;
    repeated string exchange_ids = 7;
}

message StockList {
    repeated Stock stocks = 1;
}

message Cash {
    Key key = 1;
}

message CashList {
    repeated Cash cashes = 1;
}

message Exchange {
    Key key = 1;
    string name = 2;
}

message ExchangeList {
    repeated Exchange exchanges = 1;
}
